# Generated by Django 2.1 on 2020-04-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200417_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commitnum',
            field=models.IntegerField(default=0),
        ),
    ]
