# Generated by Django 2.1 on 2020-04-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200428_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuilei',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/index/info'),
        ),
    ]
