# Generated by Django 2.1 on 2020-04-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_kuilei_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/index/info'),
        ),
    ]
